### ISSUE TITLE
Skybox not displaying in Chrome

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#10]
Test case: http://mozvr.github.io/cssvr-experiments/20150802-02/index.html
- Chrome Dev Tools > Network confirms images load successfully
- Firefox Nightly June 30 CSS VR build displays Skybox correctly

**Comment by jcarpenter** [comment]
This is probably due to use of variables for skybox panel sizes. Per http://caniuse.com/#search=variables, these are not supported in Chrome. For sake of cross browser compatibility will need to polyfill, use SASS, or switch to vanilla CSS.

**Comment by dmarcos** [comment]
Yes, this is due to the lack of support of css-variables in Chrome. Nothing to do here besides waiting for Google to catch up :)
