### ISSUE TITLE
Clicking anywhere in scene selects text

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#13]
Clicking in a scene (eg to drag with the mouse) selects any text that is present. Observed in Firefox Nightly June 30 build, but does not happen in Chrome.

**Comment by dmarcos** [comment]
I disabled text selection on scene. https://github.com/vr-components/css-vr-boilerplate/commit/47e6ec59ce5af2f5c1adf810ab2d6a25e4dffa72

**Comment by jcarpenter** [comment]
Resolved!
