### ISSUE TITLE
Use "grab" css cursor for mono mode?

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#16]
To provide a visual affordance for the ability to drag to look around the scene in mono mode, we could style the cursor with `grab`, `all-scroll`, `move`, or something similar.

eg: `cursor: grab;`

**Comment by dmarcos** [comment]
Done! https://github.com/vr-components/css-vr-boilerplate/commit/d86f4b8f31efcb7e75245ace24d179704e38be46
