### ISSUE TITLE
Eliminate mouse look rolling

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#3]
Mouse look should only effect pitch and yaw on the current forward vector. It should not effect roll. As demonstrated in this Three.js pointer lock example: http://threejs.org/examples/misc_controls_pointerlock.html

Currently mouse look effects the pitch of the camera if the mouse is in the center of the screen, but effects roll as the mouse moves towards the left and right sides.

**Comment by dmarcos** [comment]
Gimbal lock issues :S I made this same mistake like a million times already. See if I learn from this one.

This should be fixed now. 

https://github.com/vr-components/css-vr-boilerplate/commit/94155f636c8ad499465ac47bfdbcda46ba596789

@jcarpenter Can you verify it it's working for you now?

**Comment by dmarcos** [comment]
@jcarpenter if you can confirm that this is working for you i'll close the issue

**Comment by jcarpenter** [comment]
Resolved!
