### ISSUE TITLE
Pressing space zooms the view

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#4]
Pressing spacebar appears to zoom the view and rotate the camera downwards. Pressing it repeatedly repeats the action, and the zooming cannot be undone. The user must refresh with clear cache option (shift + command R) to clear the effect. Pressing space should not have any action.

**Comment by dmarcos** [comment]
Space events are not hooked up in the library. The browser scroll a page when pressing space. This has strange effects on the 3d transformed DOM. I disabled scrolling when pressing space.

https://github.com/vr-components/css-vr-boilerplate/commit/ad67a640215e9b7d632fad519275c68506a67f5f
