### ISSUE TITLE
Add `enter vr mode` function

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#5]
We have a zeroSensor function that can be called from `script` in body. We should have the same for entering fullscreen vr mode, empowering developers who want to implement enter VR flows (eg fullscreen buttons, key bindings, etc).

**Comment by dmarcos** [comment]
Done! 

https://github.com/vr-components/css-vr-boilerplate/commit/f580b5beb25a5946033cb67dc125bc0df7a10acc
