### ISSUE TITLE
Remove fullscreen button from boilerplate

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#6]
My sense is that defining a fullscreen button and it's layout is too prescriptive to include in the core of the boilerplate, and would be better defined in examples we distribute (along with examples of key bindings, etc).

**Comment by dmarcos** [comment]
Done! https://github.com/vr-components/css-vr-boilerplate/commit/97d3d94a4bef036469a3049e1c508eb106201fe9
