### ISSUE TITLE
Transforms not rendering in Safari

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/css-vr-boilerplate#7]
Presumably because Safari requires `-webkit-` vendor prefix for `transform`?

Clockwise: Safari 8.0.7, Chrome 44, Firefox Nightly 41:

![safari-chrome-firefox-transforms](https://cloud.githubusercontent.com/assets/1425497/8864740/7c237866-315a-11e5-93e3-4bef1cdd4859.png)

From http://vr-components.github.io/css-vr-boilerplate/examples/

**Comment by dmarcos** [comment]
I added the webkit prefixes and now it seems to work on Safari:

https://github.com/vr-components/css-vr-boilerplate/commit/cdc5200241924ce041347398b4db06665f950a66
